safe:        false
auto:        false
server:      false
server_port: 4000
url:         http://localhost:4000
#url:         http://mademistakes.com

source:      .
destination: ./_site
plugins:     ./_plugins

ga_account:  UA-2011187-1

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:categories/:title.html # https://github.com/mojombo/jekyll/wiki/Permalinks

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", mademistakes.sublime-project", "mademistakes.sublime-workspace", "codekit-config.json"]