safe:   false
port:   4000
#url:    http://mademistakes.com

source:      .
destination: ./_site
plugins:     ./_plugins

ga_account:    UA-2011187-1
google_verify: geapSKtvpBNDSfXVmF09E9CnaHGglbO61r4XgLZtEmo
bing_verify:   D81F4C18A6CB3018F64D7C827D953DFD
alexa_verify:  Y5DYjZ4VWlrQzBP5kcQJeOKLNas

future:      true
lsi:         false
pygments:    true
markdown:    kramdown
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title.html

# Internal pages/posts to include in top navigation
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: PaperFaces
    url: /articles/paperfaces-ipad-portrait-project.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "mademistakes.sublime-project", "mademistakes.sublime-workspace", "codekit-config.json", "Gemfile", "Gemfile.lock", "README.md"]